
import Database.Vendor;
import Database.VendorDao;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class EditVendor extends javax.swing.JPanel {

    /**
     * Creates new form VenderShowSearch
     */
    Vendor vendor;
    public EditVendor(int id) {
        ///test//
        
        initComponents();
        vendor = VendorDao.getVendor(id);
        venName.setText(vendor.getVanName());
        venAddress.setText(vendor.getVenAddress());
        venTel.setText(vendor.getVenTel());
        venEmail.setText(vendor.getVenEmail());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        venName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        venAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        venTel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        venEmail = new javax.swing.JTextField();
        confirmEditVendor = new javax.swing.JButton();
        cancelAddVendor = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(930, 410));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ชื่อบริษัท :");

        venName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("แก้ไขบริษัทคู่ค้า");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("ที่อยู่ :");

        venAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("เบอร์โทร :");

        venTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("E-mail :");

        venEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        confirmEditVendor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        confirmEditVendor.setText("ยืนยัน");
        confirmEditVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmEditVendorActionPerformed(evt);
            }
        });

        cancelAddVendor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelAddVendor.setText("ยกเลิก");
        cancelAddVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddVendorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(venAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(confirmEditVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cancelAddVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(venName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(venTel))
                            .addComponent(venEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(venName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(venAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(venTel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(venEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confirmEditVendor)
                            .addComponent(cancelAddVendor))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmEditVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmEditVendorActionPerformed
       updateVendor();
    }//GEN-LAST:event_confirmEditVendorActionPerformed

    private void cancelAddVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAddVendorActionPerformed
       clearVendor();
    }//GEN-LAST:event_cancelAddVendorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelAddVendor;
    private javax.swing.JButton confirmEditVendor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField venAddress;
    private javax.swing.JTextField venEmail;
    private javax.swing.JTextField venName;
    private javax.swing.JTextField venTel;
    // End of variables declaration//GEN-END:variables

    private void updateVendor() {
         if(!venName.getText().equals("")&&!venAddress.getText().equals("")&&!venTel.getText().equals("")&&!venEmail.getText().equals("")){
            Vendor newVendor = new Vendor();
            newVendor.setVenID(vendor.getVenID());
            newVendor.setVanName(venName.getText());
            newVendor.setVenAddress(venAddress.getText());
            newVendor.setVenTel(venTel.getText());
            newVendor.setVenEmail(venEmail.getText());
            VendorDao.update(newVendor);
            JOptionPane.showMessageDialog(this, "แก้ไขบริษัท " + newVendor.getVanName() + "เรียบร้อยแล้ว");
        }else{
            JOptionPane.showMessageDialog(this, "กรุณากรอกข้อมูลให้ถูกต้อง");
        }
    }
    private void clearVendor() {
        venName.setText("");
        venAddress.setText("");
        venTel.setText("");
        venEmail.setText("");
    }
}
