
import Database.User;
import Database.UserTableModel;
import Database.userDao;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author informatics
 */
public class employeesSearch extends javax.swing.JPanel {

    /**
    
     */
    UserTableModel userTableModel = new UserTableModel();
    public employeesSearch() {
        initComponents();
        userTableModel.setData(userDao.getUsers());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanemanuCustomer = new javax.swing.JScrollPane();
        Tableviewemp = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameSearchEmployees = new javax.swing.JTextField();
        SearchEmployees = new javax.swing.JButton();
        SearchAllEmployees = new javax.swing.JButton();

        PanemanuCustomer.setBackground(new java.awt.Color(255, 255, 255));

        Tableviewemp.setModel(userTableModel);
        PanemanuCustomer.setViewportView(Tableviewemp);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ชื่อ:");

        nameSearchEmployees.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        SearchEmployees.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SearchEmployees.setText("ค้นหา");
        SearchEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchEmployeesActionPerformed(evt);
            }
        });

        SearchAllEmployees.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SearchAllEmployees.setText("ค้นหาทั้งหมด");
        SearchAllEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchAllEmployeesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nameSearchEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(SearchEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchAllEmployees)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameSearchEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(SearchAllEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanemanuCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanemanuCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SearchAllEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchAllEmployeesActionPerformed
      
    }//GEN-LAST:event_SearchAllEmployeesActionPerformed

    private void SearchEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchEmployeesActionPerformed
        searchEmp();
    }//GEN-LAST:event_SearchEmployeesActionPerformed

    private void searchEmp() throws HeadlessException {
        ArrayList<User> empTableList =  new ArrayList<User>();
        ArrayList<User> empList = userDao.getUsers();
        User getEmp = new User();
        int item = 0;
        for (int i = 0; i < empList.size(); i++) {
            if (empList.get(i).getEmpName().equals(nameSearchEmployees.getText())) {
                getEmp = userDao.getUser(empList.get(i).getEmpID());
                
                empTableList.add(getEmp);
                userTableModel.setData(empTableList);
                item = 1;
                
            }
        }
        
        if (item == 0) {
            JOptionPane.showMessageDialog(this, "ไม่มีพนักงานชื่อ "+nameSearchEmployees.getText());
            userTableModel.setData(userDao.getUsers());
            nameSearchEmployees.setText("");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane PanemanuCustomer;
    private javax.swing.JButton SearchAllEmployees;
    private javax.swing.JButton SearchEmployees;
    private javax.swing.JTable Tableviewemp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nameSearchEmployees;
    // End of variables declaration//GEN-END:variables
}
