
import Database.Vendor;
import Database.VendorDao;
import Database.VendorTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class ManagementVendor extends javax.swing.JPanel {

    /**
     * Creates new form ManagementEmployess
     */
    
    VendorTableModel vendorTableModel = new VendorTableModel();
    public ManagementVendor() {
        initComponents();
        updateTable();
    }
    public void updateTable(){
        vendorTableModel.setData(VendorDao.getVendor());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Venderscoll = new javax.swing.JScrollPane();
        vendorTable = new javax.swing.JTable();
        AddVendor = new javax.swing.JButton();
        searchAll = new javax.swing.JButton();
        EditVendor = new javax.swing.JButton();
        DeleteVendor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchnameVendor = new javax.swing.JTextField();
        searchVendor = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(950, 530));

        jPanel3.setPreferredSize(new java.awt.Dimension(960, 530));

        vendorTable.setModel(vendorTableModel);
        vendorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vendorTableMouseClicked(evt);
            }
        });
        Venderscoll.setViewportView(vendorTable);

        AddVendor.setText("เพิ่มบริษัท");
        AddVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVendorActionPerformed(evt);
            }
        });

        searchAll.setText("ดูบริษัท");
        searchAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAllActionPerformed(evt);
            }
        });

        EditVendor.setText("แก้ไขบริษัท");
        EditVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditVendorActionPerformed(evt);
            }
        });

        DeleteVendor.setText("ลบบริษัท");
        DeleteVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteVendorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ชื่อบริษัท:");

        searchnameVendor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        searchVendor.setText("ค้นหาบริษัท");
        searchVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchVendorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(searchAll, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EditVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchnameVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Venderscoll)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchnameVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(searchVendor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchAll, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Venderscoll, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1342, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAllActionPerformed
        Venderscoll.setViewportView(new TableVender());
        updateTable();
    }//GEN-LAST:event_searchAllActionPerformed
static int id;
    private void EditVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditVendorActionPerformed
        try{
        Venderscoll.setViewportView(new EditVendor(id));
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "เลือกบริษัทที่ต้องการแก้ไข!!");
        }
    }//GEN-LAST:event_EditVendorActionPerformed

    private void AddVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVendorActionPerformed
       Venderscoll.setViewportView(new registerVendor());
    }//GEN-LAST:event_AddVendorActionPerformed

    private void searchVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchVendorActionPerformed
        ArrayList<Vendor> tableList =  new ArrayList<Vendor>();
        ArrayList<Vendor> vendorList = VendorDao.getVendor();
                    Vendor getVendor = new Vendor();
                    int item = 0;
                    for (int i = 0; i < vendorList.size(); i++) {
                        if (vendorList.get(i).getVanName().equals(searchnameVendor.getText())) {
                            getVendor = VendorDao.getVendor(vendorList.get(i).getVenID());
                            
                            tableList.add(getVendor);
                            vendorTableModel.setData(tableList);
                            item = 1;
                            
                        }
                    }
                    
                    if (item == 0) {
                        JOptionPane.showMessageDialog(this, "ไม่มีบริษัท "+searchnameVendor.getText());
                        vendorTableModel.setData(VendorDao.getVendor());
                        searchnameVendor.setText("");
                    }
    }//GEN-LAST:event_searchVendorActionPerformed

    private void vendorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendorTableMouseClicked
        String idStr = vendorTable.getValueAt(vendorTable.getSelectedRow(), 0).toString();
        id = Integer.parseInt(idStr);
        System.out.println(id);
    }//GEN-LAST:event_vendorTableMouseClicked

    private void DeleteVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteVendorActionPerformed
        try{
        JOptionPane.showMessageDialog(this,"ลบบริษัท "+VendorDao.getVendor(id).getVanName()+" เรียบร้อยแล้ว");
        VendorDao.delete(VendorDao.getVendor(id));
        updateTable();
        Venderscoll.setViewportView(new TableVender());
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "เลือกบริษัทที่ต้องการลบ!!");
        }
    }//GEN-LAST:event_DeleteVendorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddVendor;
    private javax.swing.JButton DeleteVendor;
    private javax.swing.JButton EditVendor;
    private javax.swing.JScrollPane Venderscoll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton searchAll;
    private javax.swing.JButton searchVendor;
    private javax.swing.JTextField searchnameVendor;
    private javax.swing.JTable vendorTable;
    // End of variables declaration//GEN-END:variables
}
