
import Database.Orders;
import Database.OrdersDao;
import Database.Orders_Detail;
import Database.Orders_DetailDao;
import Database.Product;
import Database.ProductTableModel;
import Database.TableOrder_Detail;
import Database.basket;
import Database.productDao;
import com.sun.org.apache.xalan.internal.xsltc.DOM;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */
public class OrderProduct extends javax.swing.JPanel {

    /**
     * Creates new form OrderProduct
     */
    int index = -1;
    TableOrder_Detail tableOrder_Detail = new TableOrder_Detail();
    ProductTableModel productTableModel = new ProductTableModel();
    ArrayList<Orders_Detail> OD = new ArrayList<Orders_Detail>();
    int empID;

    public OrderProduct(int id) {
        initComponents();
        empID = id;

        productTableModel.setData(productDao.getProducts());
        tableOrder_Detail.setData(OD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1080, 450));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("จำนวน : ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("ค้นหาสินค้า");

        jButton2.setText("ลบสินค้า");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("สั่งซื้อ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("เพิ่มลงตระกร้า");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(tableOrder_Detail);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton4.setText("ค้นหา");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("ค้นหาสินค้า : ");

        jTable2.setModel(productTableModel);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(23, 23, 23))
                        .addComponent(jLabel12)))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel12)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (index != -1) {
            for (int i = 0; i < OD.size(); i++) {
                if (OD.get(i).getOrders_detailID() == index) {
                    OD.remove(i);
                    break;
                }
            }

            ArrayList<Orders_Detail> ne = new ArrayList<Orders_Detail>();

            ne = OD;
            for (int i = 0; i < ne.size(); i++) {

                ne.get(i).setOrders_detailID(i);

            }
            System.out.println(ne);
            OD = ne;
            tableOrder_Detail.setData(OD);
            index = -1;

        } else {
            JOptionPane.showMessageDialog(this, "เลือกสินค้าที่จะลบ!!!");
        }


    }//GEN-LAST:event_jButton2ActionPerformed


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        String ProName = jTextField7.getText();

        if (!ProName.equals("")) {
            ArrayList<Product> product = new ArrayList<Product>();
            ArrayList<Product> products = productDao.getProducts();

            int item = 0;
            for (int i = 0; i < products.size(); i++) {
                if (products.get(i).getProName().equals(ProName)) {

                    product.add(products.get(i));
                    productTableModel.setData(product);
                    item = 1;

                }
            }

            if (item == 0) {
                JOptionPane.showMessageDialog(this, "ไม่มีสินค้า!!!");
                productTableModel.setData(productDao.getProducts());

            }
        } else {
            JOptionPane.showMessageDialog(this, "ไม่มีสินค้า!!!");
            productTableModel.setData(productDao.getProducts());
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    int Dseart = 0;
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:

        String idStr = jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString();
        int id = Integer.parseInt(idStr);
        Product pro = productDao.getProduct(id);

        Dseart = pro.getProductID();

        jLabel12.setText("สินค้า : " + pro.getProName());


    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (Dseart != 0) {
            int item = Integer.valueOf(jComboBox2.getSelectedItem().toString());
            int a = 0;
            Orders_Detail od = new Orders_Detail();
            for (int i = 0; i < OD.size(); i++) {
                if (OD.get(i).getProductID() == Dseart) {

                    OD.get(i).setOrdersDetailSum(item + OD.get(i).getOrdersDetailSum());
                    OD.get(i).setOrdersDatailPriceAll(productDao.getProduct(Dseart).getProPrice()*OD.get(i).getOrdersDetailSum());
                    tableOrder_Detail.setData(OD);

                    a++;
                    break;
                }
            }
            if (a == 0) {
                od.setOrders_detailID(OD.size());
                od.setOrdersDetailSum(item);
                od.setProductID(Dseart);
                int price = 0;
                for (int i = 0; i < item; i++) {
                    price = price + (productDao.getProduct(Dseart).getProPrice()*od.getOrdersDetailSum());
                }
                od.setOrdersDatailPriceAll(price);
                od.setOrdersID(0);
                OD.add(od);
                tableOrder_Detail.setData(OD);
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        String idStr = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        int id = Integer.parseInt(idStr);
        index = id;


    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int price = 0;
        if (!OD.isEmpty()) {
            for (int i = 0; i < OD.size(); i++) {
                price = price + OD.get(i).getOrdersDatailPriceAll();
            }
            Orders add = new Orders();
            add.setEmpID(empID);
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            LocalDate localDate = LocalDate.now();
            //2016/11/16
            add.setOrderDate(dtf.format(localDate));
            add.setPayProductTotal(price);
            int idO = OrdersDao.insert(add);
            for (int i = 0; i < OD.size(); i++) {
                Orders_Detail oo = new Orders_Detail();
                oo = OD.get(i);
                oo.setOrdersID(idO);
                
                Orders_DetailDao.insert(oo);
            }
            OD = new ArrayList<Orders_Detail>();
            tableOrder_Detail.setData(OD);
            JOptionPane.showMessageDialog(this, "สั่งซื้อสำเร็จ!!!");
        } else {
            JOptionPane.showMessageDialog(this, "ไม่มีสินค้า!!!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
