/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author informatics
 */
public class Pbilcartpanel extends javax.swing.JPanel {

    /**
     * Creates new form billPanel
     */
    public Pbilcartpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        productId = new javax.swing.JLabel();
        getProductId = new javax.swing.JTextField();
        productName = new javax.swing.JLabel();
        getProductName = new javax.swing.JTextField();
        price = new javax.swing.JLabel();
        getPrice = new javax.swing.JTextField();
        totalPrice = new javax.swing.JLabel();
        getTotalPrice = new javax.swing.JTextField();
        staffName = new javax.swing.JLabel();
        getStaffName = new javax.swing.JTextField();
        dateTime = new javax.swing.JLabel();
        getDateTime = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Bill Detail");

        productId.setText("ID สินค้า :");

        getProductId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getProductIdActionPerformed(evt);
            }
        });

        productName.setText("ชื่อสินค้า :");

        getProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getProductNameActionPerformed(evt);
            }
        });

        price.setText("ราคา :");

        getPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPriceActionPerformed(evt);
            }
        });

        totalPrice.setText("ราคาทั่งหมด :");

        getTotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTotalPriceActionPerformed(evt);
            }
        });

        staffName.setText("ผู้ออกใบเสร็จ :");

        getStaffName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getStaffNameActionPerformed(evt);
            }
        });

        dateTime.setText("วันที่ :");

        getDateTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getDateTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productName)
                        .addGap(32, 32, 32)
                        .addComponent(getProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productId)
                        .addGap(32, 32, 32)
                        .addComponent(getProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(price)
                        .addGap(32, 32, 32)
                        .addComponent(getPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalPrice)
                        .addGap(32, 32, 32)
                        .addComponent(getTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(staffName)
                        .addGap(32, 32, 32)
                        .addComponent(getStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateTime)
                        .addGap(32, 32, 32)
                        .addComponent(getDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productId)
                    .addComponent(getProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productName)
                    .addComponent(getProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price)
                    .addComponent(getPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPrice)
                    .addComponent(getTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffName)
                    .addComponent(getStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTime)
                    .addComponent(getDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void getProductIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getProductIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getProductIdActionPerformed

    private void getProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getProductNameActionPerformed

    private void getPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getPriceActionPerformed

    private void getTotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getTotalPriceActionPerformed

    private void getStaffNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getStaffNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getStaffNameActionPerformed

    private void getDateTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getDateTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getDateTimeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateTime;
    private javax.swing.JTextField getDateTime;
    private javax.swing.JTextField getPrice;
    private javax.swing.JTextField getProductId;
    private javax.swing.JTextField getProductName;
    private javax.swing.JTextField getStaffName;
    private javax.swing.JTextField getTotalPrice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel price;
    private javax.swing.JLabel productId;
    private javax.swing.JLabel productName;
    private javax.swing.JLabel staffName;
    private javax.swing.JLabel totalPrice;
    // End of variables declaration//GEN-END:variables
}
