
import Database.BillCustomer;
import Database.BillCustomerDao;
import Database.Bill_Detail;
import Database.Bill_DetailDao;
import Database.Payment;
import Database.PaymentDao;
import Database.basket;
import Database.basketTable;
import Database.productDao;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ASUS
 */
public class Pcart extends javax.swing.JPanel {

    /**
     * Creates new form cart
     */
    PsearchProductPanel as;
    ArrayList<basket> basket = new ArrayList<basket>();
    basketTable basetTable = new basketTable();
    int cusID, empIndex, price;

    public Pcart(ArrayList<basket> basket, int cusID, int empIndex, int price) {
        initComponents();
        this.basket = basket;
        this.cusID = cusID;
        this.empIndex = empIndex;
        this.price = price;
        basetTable.setData(basket);
       
        jLabel3.setText("Total : " + String.valueOf(price));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tabelcartpanelscroll = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("ตระกร้าสินค้า");

        jTable2.setModel(basetTable);
        tabelcartpanelscroll.setViewportView(jTable2);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("ยืนยัน");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("ยกเลิก");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Total :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabelcartpanelscroll))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(43, 43, 43)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(401, 401, 401)
                                .addComponent(jLabel2)))
                        .addGap(0, 280, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tabelcartpanelscroll, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        confirmCart();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void confirmCart() throws HeadlessException {
        if (!basket.isEmpty()) {
            Payment pay = new Payment();
            pay.setPayTotalPrice(price);
            pay.setPromotionID(1);
            int idPar = PaymentDao.insert(pay);
            if (idPar != -1) {
                
                BillCustomer billcos = new BillCustomer();
                billcos.setPaymentID(idPar);
                billcos.setCusID(cusID);
                billcos.setEmpID(empIndex);
                int idBill = BillCustomerDao.insert(billcos);
                if (idBill != -1) {
                    
                    for (int i = 0; i < basket.size(); i++) {
                        Bill_Detail billd = new Bill_Detail();
                        billd.setBillID(idBill);
                        billd.setProductID(basket.get(i).getProductID());
                        billd.setItem(basket.get(i).getItem());
                        Bill_DetailDao.insert(billd);
                    }
                    String list = "";
                    for (int i = 0; i < basket.size(); i++) {
                        list = list + " " +productDao.getProduct(basket.get(i).getProductID()).getProName()+" "+basket.get(i).getItem()+" ชิ้น\n";
                        
                    }
                    
                    JOptionPane.showMessageDialog(this, "BillID : " + idBill + "\n" + list  + "Total : " + price + " บาท \n" );
                    basetTable.setData(basket = new ArrayList<>());
                    price = 0;
                    jLabel3.setText("Total : " + String.valueOf(price));
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "error pay");
            }
        } else {
            JOptionPane.showMessageDialog(this, "กลับไปเลือกสินค้าใหม่");
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        basketTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void basketTable() {
        basetTable.setData(basket = new ArrayList<>());
        price = 0;
        jLabel3.setText("Total : " + String.valueOf(price));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable2;
    private javax.swing.JScrollPane tabelcartpanelscroll;
    // End of variables declaration//GEN-END:variables
}
