
import Database.User;
import Database.userDao;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KiTTiWaT
 */
public class regEmployeesPanel extends javax.swing.JPanel {

    /**
     * Creates new form regEmployeesPanel
     */
    public regEmployeesPanel() {
        initComponents();
    }
    //asdfghjklqwertyuizxcvbhnjk

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        logintext = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        passwordtext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        empName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        empSurname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        empAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        empTel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        empEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        empBank = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        typeWordID = new javax.swing.JComboBox<>();
        confirmAddEmployees = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(796, 504));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("สมัครพนักงาน");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Login :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Password :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("ชื่อ : ");

        empName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("นามสกุล : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("ที่อยู่ : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("เบอร์โทร :");

        empTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empTelActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("E-mail : ");

        empEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empEmailActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("บันชีธนาคาร : ");

        empBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empBankActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("ตำแหน่ง : ");

        typeWordID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "พนักงานขาย", "พนักงานดูแลสินค้า", " " }));
        typeWordID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeWordIDActionPerformed(evt);
            }
        });

        confirmAddEmployees.setText("ยืนยัน");
        confirmAddEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmAddEmployeesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(empName)
                            .addComponent(empSurname)
                            .addComponent(empAddress)
                            .addComponent(empTel)
                            .addComponent(empEmail)
                            .addComponent(empBank)
                            .addComponent(logintext)
                            .addComponent(passwordtext)
                            .addComponent(typeWordID, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(confirmAddEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(logintext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordtext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(empSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(empAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empTel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(empEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(empBank, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeWordID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmAddEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmAddEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmAddEmployeesActionPerformed
        
        RegEmployees();

    }//GEN-LAST:event_confirmAddEmployeesActionPerformed

    private void empBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empBankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empBankActionPerformed

    private void empEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empEmailActionPerformed

    private void empTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empTelActionPerformed

    private void empNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empNameActionPerformed

    private void typeWordIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeWordIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeWordIDActionPerformed

    private User user;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmAddEmployees;
    private javax.swing.JTextField empAddress;
    private javax.swing.JTextField empBank;
    private javax.swing.JTextField empEmail;
    private javax.swing.JTextField empName;
    private javax.swing.JTextField empSurname;
    private javax.swing.JTextField empTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField logintext;
    private javax.swing.JTextField passwordtext;
    private javax.swing.JComboBox<String> typeWordID;
    // End of variables declaration//GEN-END:variables

    private void RegEmployees() {
//        User newuser1 = new User();
//        newuser1.setLoginName(logintext.getText());
//        newuser1.setPassword(passwordtext.getText());
//        newuser1.setEmpName(empName.getText());
//        newuser1.setEmpSername(empSurname.getText());
//        newuser1.setEmpAddress(empAddress.getText());
//        newuser1.setEmpTel(empTel.getText());
//        newuser1.setEmpEmail(empEmail.getText());
//        newuser1.setEmpBank(Integer.parseInt(empBank.getText()));
//        newuser1.setTypeWordID(typeWordID.getSelectedIndex()+2);
//        userDao.insert(newuser1);
//        //JOptionPane.showMessageDialog(null,"สมัครพนักงาน "+newuser1.getEmpName()+" "+newuser1.getEmpSername()+" เรียบร้อยแล้ว");
//        JOptionPane.showMessageDialog(null,newuser1);

        try{
            User newuser1 = new User();
            newuser1.setLoginName(logintext.getText());
            newuser1.setPassword(passwordtext.getText());
            newuser1.setEmpName(empName.getText());
            newuser1.setEmpSername(empSurname.getText());
            newuser1.setEmpAddress(empAddress.getText());
            newuser1.setEmpTel(empTel.getText());
            newuser1.setEmpEmail(empEmail.getText());
            newuser1.setEmpBank(Integer.parseInt(empBank.getText()));
            newuser1.setTypeWordID(typeWordID.getSelectedIndex()+2);
            newuser1.setWorkStatus("ทำงาน");
            userDao.insert(newuser1);
            JOptionPane.showMessageDialog(null,"สมัครพนักงาน "+newuser1.getEmpName()+" "+newuser1.getEmpSername()+" เรียบร้อยแล้ว");
            
            
            
            
            reForm();
            
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"กรุณากรอกข้อมูลให้ถูกต้อง");
        }
    
        
    }

    private void reForm() {
        logintext.setText("");
        passwordtext.setText("");
        empName.setText("");
        empSurname.setText("");
        empAddress.setText("");
        empTel.setText("");
        empEmail.setText("");
        empBank.setText("");
    }
}
