
import Database.Vendor;
import Database.VendorDao;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Admin
 */
public class registerVendor extends javax.swing.JPanel {

    /**
     * Creates new form VenderShowSearch
     */
    public registerVendor() {
        initComponents();
        //tast/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        venName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        venAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        venTel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        venEmail = new javax.swing.JTextField();
        confirmAddVendor = new javax.swing.JButton();
        cancelAddVendor = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(930, 410));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("เพิ่มบริษัทคู่ค้า");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ชื่อบริษัท :");

        venName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("ที่อยู่ :");

        venAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("เบอร์โทร :");

        venTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("E-mail :");

        venEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        confirmAddVendor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        confirmAddVendor.setText("ยืนยัน");
        confirmAddVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmAddVendorActionPerformed(evt);
            }
        });

        cancelAddVendor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelAddVendor.setText("ยกเลิก");
        cancelAddVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddVendorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(venEmail)
                                .addComponent(venTel)
                                .addComponent(venAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(venName, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(confirmAddVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelAddVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55)))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(venName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(venAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(venTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(venEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmAddVendor)
                    .addComponent(cancelAddVendor))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmAddVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmAddVendorActionPerformed
        insertVendor();
    }//GEN-LAST:event_confirmAddVendorActionPerformed

    private void cancelAddVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAddVendorActionPerformed
        clearVendor();
    }//GEN-LAST:event_cancelAddVendorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelAddVendor;
    private javax.swing.JButton confirmAddVendor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField venAddress;
    private javax.swing.JTextField venEmail;
    private javax.swing.JTextField venName;
    private javax.swing.JTextField venTel;
    // End of variables declaration//GEN-END:variables

    private void insertVendor() {
        if(!venName.getText().equals("")&&!venAddress.getText().equals("")&&!venTel.getText().equals("")&&!venEmail.getText().equals("")){
            Vendor newVendor = new Vendor();
            newVendor.setVanName(venName.getText());
            newVendor.setVenAddress(venAddress.getText());
            newVendor.setVenTel(venTel.getText());
            newVendor.setVenEmail(venEmail.getText());
            VendorDao.insert(newVendor);
            JOptionPane.showMessageDialog(this, "เพิ่มบริษัท " + newVendor.getVanName() + "เรียบร้อยแล้ว");
        }else{
            JOptionPane.showMessageDialog(this, "กรุณากรอกข้อมูลให้ถูกต้อง");
        }
    }

    private void clearVendor() {
        venName.setText("");
        venAddress.setText("");
        venTel.setText("");
        venEmail.setText("");
    }
}
