
import Database.BillCustomer;
import Database.BillCustomerDao;
import Database.Bill_Detail;
import Database.Bill_DetailDao;
import Database.Product;
import Database.productDao;
import Database.sellhistorryTable;
import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javafx.scene.control.Alert;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import static org.omg.CORBA.PolicyListHelper.id;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ASUS
 */
public class saleHistory extends javax.swing.JPanel {

    /**
     * Creates new form saleHistory
     */
    public saleHistory() {
        initComponents();
        sellhistorryTable.setData(BillCustomerDao.getBillCustomer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    sellhistorryTable sellhistorryTable = new sellhistorryTable();


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saleHistory = new javax.swing.JLabel();
        searc = new javax.swing.JTextField();
        searchDate1 = new javax.swing.JButton();
        searchDate = new javax.swing.JButton();
        viewtabelsalejscroll = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(960, 530));

        saleHistory.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        saleHistory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saleHistory.setText("ประวัติการขาย");

        searc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searcActionPerformed(evt);
            }
        });

        searchDate1.setText("ค้นหา");
        searchDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDate1ActionPerformed(evt);
            }
        });

        searchDate.setText("ดู");
        searchDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDateActionPerformed(evt);
            }
        });

        viewtabelsalejscroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewtabelsalejscrollMouseClicked(evt);
            }
        });

        jTable1.setModel(this.sellhistorryTable);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        viewtabelsalejscroll.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ค้นหา ID BILL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(viewtabelsalejscroll))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(searc, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchDate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(379, 379, 379)
                                .addComponent(saleHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saleHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(searchDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(viewtabelsalejscroll, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        setSaleTable();
    }//GEN-LAST:event_jTable1MouseClicked

    private void setSaleTable() throws NumberFormatException {
        String idStr = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();

        billID = Integer.parseInt(idStr);

    }

    private void searchDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDateActionPerformed
        getBillDetail();
    }//GEN-LAST:event_searchDateActionPerformed

    private void getBillDetail() {

        if (billID != -1) {
            ArrayList<Bill_Detail> list = Bill_DetailDao.getBill_Details();
            ArrayList<Bill_Detail> r = new ArrayList<Bill_Detail>();

            for (int i = 0; i < list.size(); i++) {

                if (billID == list.get(i).getBillID()) {
                    r.add(list.get(i));
                }

            }
            billID = -1;
            viewtabelsalejscroll.setViewportView(new Detail_Bill_Show(r));

        } else {
            billID = -1;
            JOptionPane.showMessageDialog(this, "เลือกBill!!!");
        }

    }

    private void searchDate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDate1ActionPerformed
        searchBill();
    }//GEN-LAST:event_searchDate1ActionPerformed

    private void searchBill() throws HeadlessException, NumberFormatException {
        String spro = searc.getText();

        if (!spro.equals("")) {
            int id1 = Integer.parseInt(spro);
            ArrayList<BillCustomer> b = new ArrayList<BillCustomer>();
            BillCustomer billd = BillCustomerDao.getBillCustomer(id1);
            b.add(billd);
            int a = b.size();
            System.out.println(a + "" + b);
            if (billd == null) {
                JOptionPane.showMessageDialog(this, "ไม่พบbill!!!");
            } else {
                sellhistorryTable.setData(b);
            }
        } else {
            sellhistorryTable.setData(BillCustomerDao.getBillCustomer());
        }
    }

    private void searcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searcActionPerformed
    static int billID = -1;
    private void viewtabelsalejscrollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewtabelsalejscrollMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_viewtabelsalejscrollMouseClicked
    static int id = -1;
    private BillCustomer bill;
    private int a;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel saleHistory;
    private javax.swing.JTextField searc;
    private javax.swing.JButton searchDate;
    private javax.swing.JButton searchDate1;
    private javax.swing.JScrollPane viewtabelsalejscroll;
    // End of variables declaration//GEN-END:variables

    private void toFrom(BillCustomer bill) {

        a = bill.getBillID();

        //To change body of generated methods, choose Tools | Templates.
    }
}
