
import Database.VendorDao;
import Database.VendorTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class TableVender extends javax.swing.JPanel {

    /**
     * Creates new form TableVender
     */
    ManagementVendor mm = new ManagementVendor();
    VendorTableModel vendorTableModel = new VendorTableModel();
    public TableVender() {
        initComponents();
        updateTable();
    }
    public void updateTable(){
        vendorTableModel.setData(VendorDao.getVendor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tablevendor = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(925, 410));

        Tablevendor.setModel(vendorTableModel);
        Tablevendor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablevendorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tablevendor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TablevendorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablevendorMouseClicked
        String idStr = Tablevendor.getValueAt(Tablevendor.getSelectedRow(), 0).toString();
        mm.id = Integer.parseInt(idStr);
        System.out.println(mm.id);
    }//GEN-LAST:event_TablevendorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablevendor;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
